config/routes.rb
Rails.application.routes.draw do
  
  # get 'web/index'
  # get 'shopping_carts/index'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/mypage'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    # root :to => "users/sessions#new"
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post   "cart/create", :to => "shopping_carts#create"
      delete "cart", :to => "shopping_carts#destroy"
      get "mypage", :to => "users#mypage"
      get "mypage/edit", :to => "users#edit"
      get "mypage/address/edit", :to => "users#edit_address"
      put "mypage", :to => "users#update"
      get "mypage/edit_password", :to =>"users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get  "mypage/favorite", :to => "users#favorite"
    end
  end
  
  resources :products do
    member do
      post :favorite
    end
    resources :reviews, only: [:create]
  end
end
  

app/views/layouts/_footer.html.erb
<!--mx-autoクラスを追加することで「Samazon」のロゴを中央寄せにしている点
<nav>タグにfixed-bottomクラスを指定することでページの下部にフッターを固定している-->
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-bottom mt-5">
  <%= link_to root_path, class: "navbar-brand mx-auto" do %>
    <%= image_tag "/images/logo.jpg", class: "img-fuild" %>
  <% end %>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm samazon-header-container">
   <%= link_to root_path do %>
      <%= image_tag "/images/logo.jpg" %>
    <% end %>
    <form class="form-inline">
      <div class="form-group">
        <input class="form-control samazon-header-search-input">
      </div>
      <div class="input-group">
        <button type="submit" class="btn samazon-header-search-button"><i class="fas fa-search samazon-header-search-icon"></i></button>
      </div>
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-5 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <!--<li class="nav-item mr-5">-->
        <!--  <%= link_to "ログアウト", logout_path, onclick: "event.preventDefault(); document.getElementById('logout-form').submit();" %>-->
        <!--  <%= form_with url: logout_path, style: "display: none;", method: "get", id: "logout-form" do |f| %>-->
        <!--  <% end %>-->
        <!--</li>-->
        <li class="nav-item mr-5">
          <%= link_to mypage_users_path, class: "nav-link" do %>
            <i class="fas fa-user mr-1"></i><label>マイページ</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to mypage_favorite_users_path, class: "nav-link" do %>
            <i class="far fa-heart"></i>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to cart_users_path, class: "nav-link" do %>
            <i class="fas fa-shopping-cart"></i>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item mr-5">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <label>新規登録</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <hr>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="far fa-heart"></i><% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="fas fa-shopping-cart"></i><% end %>
        </li>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/_sidebar.html.erb
<div class="container">
  <% major_category_names.each do |major_category_name| %>
    <h2><%= major_category_name %></h2>
    <% categories.each do |category| %>
      <% if category.major_category_name == major_category_name %>
        <!--<label class="samazon-sidebar-category-label">-->
        <!--  <%= link_to category.name, "#" %>-->
        <!--</label>-->
        <label class="samazon-sidebar-category-label">
          <%= link_to category.name, products_path(category: category.id) %>
        </label>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV["APP_NAME"] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/1675fdf34b.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <!--renderメソッドでパーシャルテンプレートファイルを読み込ませるときは、
    ファイル名の先頭にアンダースコアはつけない-->
    <!--app/views/layouts/_header.html.erbを読み込む-->
    <!--(headerの機能は上記.erbに記述されている)-->
    <%= render partial: 'layouts/header' %>
    
    <main class="py-4 mb-5">
      <% if notice %><p class="alert alert-warning"><%= notice %></div><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
    <!--app/views/users/sessions/new.html.erbといったファイルは、
    application.html.erb内の以下の部分に差し込まれる-->
    <%= yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>